#!/bin/sh

export BROWSER="firefox"
export termbrowser="w3m"

mount /home/ylan/dyn
# jupyter lab  --NotebookApp.token=  & 
export PATH="$PATH:$HOME/Scripts"
export EDITOR="vim"
# export TERMINAL="st"
# export BROWSER="linkhandler"
# export TRUEBROWSER="firefox"
# export READER="zathura"
# export BIB="$HOME/Documents/LaTeX/uni.bib"

[ -f ~/.bashrc ] && source ~/.bashrc

 wal -Rn

 # Start graphical server if i3 not already running.
 if [ "$(tty)" = "/dev/tty1" ]; then
  pgrep -x i3 || exec startx
 fi

